<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('jobseeker_details', function (Blueprint $table) {
            $table->bigIncrements('js_id');

            $table->longText('js_firstname');
            $table->longText('js_middlename')->nullable();
            $table->longText('js_lastname');
            $table->longText('js_suffix')->nullable();
            $table->longText('js_gender');
            $table->longText('js_age');
            $table->longText('js_province')->nullable();
            $table->longText('js_city',)->nullable();
            $table->longText('js_baranggay')->nullable();
            $table->longText('js_address')->nullable();
            $table->longText('js_email')->unique();
            $table->string('js_resume')->nullable();
            $table->longText('js_contactnumber');
            $table->string('js_password');
            $table->longText('js_accstatus')->nullable();
            $table->string('js_image')->nullable();
            $table->string('js_badge')->nullable();


            // Timestamps
            $table->timestamps(); // Automatically adds created_at and updated_at fields
        });

        DB::table('jobseeker_details')->insert([
            [
                'js_firstname' => 'MARIVIC',
                'js_middlename' => 'CHOME',
                'js_lastname' => 'CABALLERO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'L.CUAYCONG STREET',
                'js_email' => 'marivic.caballero@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9487161185',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-10-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'DEN',
                'js_middlename' => 'MARK BAYA',
                'js_lastname' => 'GASPAR',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'HDA. PAZ II',
                'js_email' => 'den.gaspar@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9707208998',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-10-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JASON',
                'js_middlename' => 'GEVERO',
                'js_lastname' => 'INTONG',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'VICTORIAS',
                'js_email' => 'jason.intong@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9346552350',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-10-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'CHRISTIAN',
                'js_middlename' => 'BARRIOS',
                'js_lastname' => 'CALAYCAY',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'ZONE VI',
                'js_email' => 'christian.calaycay@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9502606713',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-10-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JHON',
                'js_middlename' => 'PAUL LAYLON',
                'js_lastname' => 'CASTRO',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'PRK. 5',
                'js_email' => 'jhon.castro@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9603960300',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-10-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'PAUL',
                'js_middlename' => 'ORIDINA',
                'js_lastname' => 'ALTEJOS',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'VICTORIAS CITY',
                'js_email' => 'paul.altejos@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9456345645',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'EDUARDO',
                'js_middlename' => 'SEBASTIAN',
                'js_lastname' => 'BUOY',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'VILLA VICTORIAS',
                'js_email' => 'eduardo.buoy@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9632188553',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JOHN',
                'js_middlename' => 'STEPHEN JUTAR',
                'js_lastname' => 'DAMIRAY',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'HDA. PATLAGAN, BRGY. PURISIMA, MANAPLA, NEGROS OCCIDENTAL',
                'js_email' => 'john.damiray@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9108789174',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'LEAH',
                'js_middlename' => 'MAY PEÑACUBA',
                'js_lastname' => 'DELA CRUZ',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA. NENANG',
                'js_email' => 'leah.delacruz@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9488164859',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'DREXVON',
                'js_middlename' => 'DAVE CARBONILLAS',
                'js_lastname' => 'DUMADA-UG',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'SITIO LUPA',
                'js_email' => 'drexvon.dumada-ug@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9074676445',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'REYNOLD',
                'js_middlename' => 'DESCARTIN',
                'js_lastname' => 'MABILOG',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'ZONE 7',
                'js_email' => 'reynold.mabilog@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9667387359',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ARIEL',
                'js_middlename' => 'ESCALERA',
                'js_lastname' => 'MACABEBE',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'SITIO BOULEVARD',
                'js_email' => 'ariel.macabebe@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9852106804',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'REY',
                'js_middlename' => 'ANTONETTE CAUSING',
                'js_lastname' => 'MILLANES',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'ZONE 5, CUBAY',
                'js_email' => 'rey.millanes@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9561669093',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'REYMAR',
                'js_middlename' => 'MUYCO',
                'js_lastname' => 'TERUEL',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'GONZAGA ST.',
                'js_email' => 'reymar.teruel@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9458092878',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JERICO',
                'js_middlename' => 'ESTEBAN',
                'js_lastname' => 'TRIBACO',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'VILLA VICTORIAS',
                'js_email' => 'jerico.tribaco@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9154917029',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'STEPHEN',
                'js_middlename' => 'RYAN',
                'js_lastname' => 'VILLANUEVA',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'FERMONT VILLAGE, BLK2',
                'js_email' => 'stephen.villanueva@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9631715171',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-08-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'KIMBERLY',
                'js_middlename' => 'PERDIGOSA',
                'js_lastname' => 'AGAEL',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PUROK PAGASA BARANGAY DAMGO E. B. MAGALONA NEGROS OCCIDENTAL',
                'js_email' => 'kimberly.agael@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9098466157',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-09-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'TEAH',
                'js_middlename' => 'SANTIAGO',
                'js_lastname' => 'FRANCO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PHASE 13 BLK 2. LOT 41 STREET. THERESE VILLAGE',
                'js_email' => 'teah.franco@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456789', // generated dummy number starting with 9
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-08-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ANGELA',
                'js_middlename' => 'MAE DENOLONG',
                'js_lastname' => 'MAGALLANES',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA.SAN ANTONIO II',
                'js_email' => 'angela.magallanes@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9153207517', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-08-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'MERRY',
                'js_middlename' => 'JOY JALIPA',
                'js_lastname' => 'PABALINAS',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA. SAN RAMON',
                'js_email' => 'merry.pabalinas@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456781', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-08-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JOYCE',
                'js_middlename' => 'MARIE ILISAN',
                'js_lastname' => 'PARREÑO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'NONE',
                'js_email' => 'joyce.parreno@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9452811462', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-08-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'KENNY',
                'js_middlename' => 'SAMSON',
                'js_lastname' => 'RAGANAS',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'PUROK 8',
                'js_email' => 'kenny.raganas@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9155211314', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-08-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'DAVID',
                'js_middlename' => 'JOHN RITO',
                'js_lastname' => 'RUBIDO',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'PUROK 6',
                'js_email' => 'david.rubido@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9567415383', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-08-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'VIJAY',
                'js_middlename' => 'JULIAN CEASAR SINORO',
                'js_lastname' => 'STA. ANA',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'SOUTH BACAYAN',
                'js_email' => 'vijay.staana@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456782', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ALLYANA',
                'js_middlename' => 'MAE CASIPLE',
                'js_lastname' => 'ANDICO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PUROK NANGKA',
                'js_email' => 'allyana.andico@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456783', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JESSA',
                'js_middlename' => 'TEGUIHAN',
                'js_lastname' => 'CABALLERO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'RELOCATION SITE',
                'js_email' => 'jessa.caballero@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456784', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JOSHUA',
                'js_middlename' => 'ACALLAR',
                'js_lastname' => 'DOMANIEL',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'HDA PAZ I',
                'js_email' => 'joshua.domaniel@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456785', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'QUEENE',
                'js_middlename' => null,
                'js_lastname' => 'ELISAN',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'SALVACION VILLAGE',
                'js_email' => 'queene.elisan@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456786', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'RICHLIE',
                'js_middlename' => 'FAITH',
                'js_lastname' => 'GERMINO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'VILLA VICTORIAS',
                'js_email' => 'richlie.germino@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456787',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-12-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ANGELIKA',
                'js_middlename' => 'LIMPANGOG',
                'js_lastname' => 'GUILIPA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'AMADO ALFARO ST.',
                'js_email' => 'angelika.guilipa@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456788', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-12-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'FAITH',
                'js_middlename' => 'PONTINO',
                'js_lastname' => 'MONTECILLO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA IDEAL',
                'js_email' => 'faith.montecillo@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456789', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-01-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'PRINCESS',
                'js_middlename' => 'KERL PANGADLO',
                'js_lastname' => 'MORALES',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'SO. JULIANA',
                'js_email' => 'princess.morales@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456790', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-01-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JILLIAN',
                'js_middlename' => 'VASQUEZ',
                'js_lastname' => 'VILLARIAS',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BRGY GUINHALARAN',
                'js_email' => 'jillian.villarias@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456791', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-01-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'THERESA',
                'js_middlename' => 'LUCINE',
                'js_lastname' => 'VISTO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PRK. KAPAYAS',
                'js_email' => 'theresa.visto@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9464015041', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-01-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'IRESH',
                'js_middlename' => 'SEQUISA',
                'js_lastname' => 'ALBADA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BARANGAY 10',
                'js_email' => 'iresh.albada@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9957468300', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-01-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'SHELALYN',
                'js_middlename' => 'PASIGNAHIN',
                'js_lastname' => 'ALVAREZ',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA MANTA-ONON',
                'js_email' => 'shelalyn.alvarez@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9965029305', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-01-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'DOROTHEA',
                'js_middlename' => 'NAVAJA',
                'js_lastname' => 'ALVISSI',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BARANGAY 13',
                'js_email' => 'dorothea.alvissi@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9066584452', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-02-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ROBINA',
                'js_middlename' => 'NUDA',
                'js_lastname' => 'BALDAVA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PHASE I, BANDONG VILLAGE',
                'js_email' => 'robina.baldava@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9218161628', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-02-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'LORAINE',
                'js_middlename' => 'GRACE JUMBAS',
                'js_lastname' => 'BANHAO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA. ROMANA',
                'js_email' => 'loraine.banhao@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9668307292', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-02-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'EFREN',
                'js_middlename' => 'BAYLOSIS',
                'js_lastname' => 'BELONIO',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'CUAYCONG',
                'js_email' => 'efren.belonio@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9452848887', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-02-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'DOMY',
                'js_middlename' => 'MA DY GUASO',
                'js_lastname' => 'BUENCUCHILLO',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'GONZAGA STREET',
                'js_email' => 'domy.buencuchillo@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456792', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-02-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'PATER',
                'js_middlename' => 'JOHN SOMBERO',
                'js_lastname' => 'BURGOS',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'GRACIA STREET',
                'js_email' => 'pater.burgos@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456793', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-02-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ELLA',
                'js_middlename' => 'MAE QUINDAP',
                'js_lastname' => 'BUSTAMANTE',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PASIL',
                'js_email' => 'ella.bustamante@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456794', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-03-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'GUIA',
                'js_middlename' => 'DELA CRUZ',
                'js_lastname' => 'CADAVERO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'ANTONIO LUNA INTERIOR',
                'js_email' => 'guia.cadavero@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9465739211', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-03-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ELNA',
                'js_middlename' => 'CAYETANO',
                'js_lastname' => 'CAÑETE',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BRGY. XIII, VICTORIAS CITY NEG. OCC.',
                'js_email' => 'elna.canete@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9109718272', // removed starting 0 and dash
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-03-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'LEONY',
                'js_middlename' => 'MAE ADORIO',
                'js_lastname' => 'CANOY',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BINANLUTAN',
                'js_email' => 'leony.canoy@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456795', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-03-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'CHERRYLYN',
                'js_middlename' => 'UY',
                'js_lastname' => 'CATALAN',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BRGY 3',
                'js_email' => 'cherrylyn.catalan@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456796', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-04-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'FLORY',
                'js_middlename' => 'MAE JOBAN',
                'js_lastname' => 'DALIPE',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'LOT 1 BLK. 1KADALAG-AN VILLAGE',
                'js_email' => 'flory.dalipe@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9396548391', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-04-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'LOVELY',
                'js_middlename' => 'MAY FUENTES',
                'js_lastname' => 'DE LA TORRE',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'FERMONT VILLAGE',
                'js_email' => 'lovely.delatorre@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9163572275', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-04-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ASHLEY',
                'js_middlename' => 'BEATRICE MADAMBA',
                'js_lastname' => 'DELA CRUZ',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => '#21 KALAYAAN AVENUE POST PROPER NORTHSIDE, WEST REMBO MAKATI CITY',
                'js_email' => 'ashley.delacruz@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9064823254', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-04-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JESSMAR',
                'js_middlename' => 'DIONELA',
                'js_lastname' => 'DEOFILES',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'SITIO SOOL',
                'js_email' => 'jessmar.deofiles@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9071189558', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-04-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ROSIEMAE',
                'js_middlename' => 'SAUSA',
                'js_lastname' => 'DESPUES',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA PAZ II',
                'js_email' => 'rosiemae.despu@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9952697916', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-04-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JONA',
                'js_middlename' => 'ILLUSTRISIMO',
                'js_lastname' => 'DOLAR',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PAZ AVENUE',
                'js_email' => 'jona.dolar@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456797', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-04-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'LEAH',
                'js_middlename' => 'MAE ABKILAN',
                'js_lastname' => 'DONGGON',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PUROK 6',
                'js_email' => 'leah.donggon@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9454688525', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'RONALIE',
                'js_middlename' => null,
                'js_lastname' => 'DUMAGAT',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BRGY 3',
                'js_email' => 'ronalie.dumagat@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456798', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ALLIA',
                'js_middlename' => 'JUANITAS',
                'js_lastname' => 'DUYUNGAN',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PASIL, ZONE 3-B',
                'js_email' => 'allia.duyungan@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9071732765', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ALEXANDER',
                'js_middlename' => 'ROA',
                'js_lastname' => 'ESTILO',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'PRK. 6',
                'js_email' => 'alexander.estilo@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9519739806', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'WILMA',
                'js_middlename' => 'NOTORIO',
                'js_lastname' => 'GAMBOA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'VMC SITE ZONE 4',
                'js_email' => 'wilma.gamboa@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9105385614', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JOYCE',
                'js_middlename' => 'DEQUIT',
                'js_lastname' => 'GUASIS',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'RIZAL ST',
                'js_email' => 'joyce.guaisis@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9677637893', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'FIDEMAY',
                'js_middlename' => 'GUMBAN',
                'js_lastname' => 'GUINO-O',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BANGGA-DAAN',
                'js_email' => 'fidemay.guinoo@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9519739810', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JHOANA',
                'js_middlename' => 'MAE PLAGA',
                'js_lastname' => 'GUMBOC',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'RIZAL ST',
                'js_email' => 'jhoana.gumboc@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9677637893', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'SHEM',
                'js_middlename' => 'ROSALES',
                'js_lastname' => 'GUSTILO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BUGTONG LUBI',
                'js_email' => 'shem.gustilo@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456799', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'DESIREE',
                'js_middlename' => 'MACABEBE',
                'js_lastname' => 'HERRERA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BANGGA DAAN, ZONE 6',
                'js_email' => 'desiree.herrera@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9512834662', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JOEMAR',
                'js_middlename' => 'NAVARRO',
                'js_lastname' => 'ILISAN',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'HDA. LAWA.AN',
                'js_email' => 'joemar.ilisan@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9082298565', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-05-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JULIE',
                'js_middlename' => 'ROMAY',
                'js_lastname' => 'LAUNIO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'ZONE 1',
                'js_email' => 'julie.launio@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9126841805', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'GIDEONE',
                'js_middlename' => 'OLIVO',
                'js_lastname' => 'LEGARDA',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'HDA SALOME II',
                'js_email' => 'gideone.legarda@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9306637657', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'MARICEL',
                'js_middlename' => 'LEAÑO',
                'js_lastname' => 'LORAIZ',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA. LA CONSOLACION',
                'js_email' => 'maricel.loraiz@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9152412414', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'FEL',
                'js_middlename' => 'JOHN CHAVEZ',
                'js_lastname' => 'MERCARAL',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'DE LEON STREET',
                'js_email' => 'fel.mercaral@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456789', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'RONIEL',
                'js_middlename' => 'AYUNTING',
                'js_lastname' => 'MIRANDA',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'ZONE 3A, SITIO PASIL',
                'js_email' => 'roniel.miranda@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9318264223', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'GIZELLE',
                'js_middlename' => 'NACIS',
                'js_lastname' => 'MORENO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA. SAN JOSE',
                'js_email' => 'gizelle.moreno@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9050741172', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'MARK',
                'js_middlename' => 'BRYAN DATO-ON',
                'js_lastname' => 'MUHAL',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'HDA. NENANG',
                'js_email' => 'mark.muhal@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9952711997', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'MARICON',
                'js_middlename' => 'PANISA',
                'js_lastname' => 'MUÑEZ',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA. PAZ 1',
                'js_email' => 'maricon.munez@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9505355103', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JOHN',
                'js_middlename' => 'CJ ARROZ',
                'js_lastname' => 'PARCON',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'BRGY ESTADO',
                'js_email' => 'john.parcon@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9816479567',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'RENALYN',
                'js_middlename' => 'PANES',
                'js_lastname' => 'ROLDAN',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'ZONE 3',
                'js_email' => 'renalyn.roldan@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '963036828',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-06-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'REBECCA',
                'js_middlename' => 'ELHIS ESTRELLA',
                'js_lastname' => 'SEGURA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'GUIA ST. CANETOWN SUBD.',
                'js_email' => 'rebecca.segura@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9666341609', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JAIME',
                'js_middlename' => 'HECHANOVA',
                'js_lastname' => 'SIOCON',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'HDA. SALOME II',
                'js_email' => 'jaime.siocon@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9480382931', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'JOWELLA',
                'js_middlename' => 'UY',
                'js_lastname' => 'TANG',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BRGY 3',
                'js_email' => 'jowella.tang@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456789', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'MARY',
                'js_middlename' => 'LIZ BIANTAN',
                'js_lastname' => 'TANUTAN',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BINANLUTAN PHASE 2',
                'js_email' => 'mary.tanutan@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9455136028', // removed starting 0
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'RHENALYN',
                'js_middlename' => 'MOREÑO',
                'js_lastname' => 'TIRAMBULO',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'CUAYCONG',
                'js_email' => 'rhenalyn.tirambulo@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9123456789', // generated dummy number
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'EDEN',
                'js_middlename' => 'DELOS SAÑEZ',
                'js_lastname' => 'TRIESTE',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'PUROK 4',
                'js_email' => 'eden.trieste@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9101568774',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'ANAMHOR',
                'js_middlename' => 'SALMORIN',
                'js_lastname' => 'TUBIERA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA. SAN JOSE CONCEPCION',
                'js_email' => 'anamhortubiera@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9560866743',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'NORONESA',
                'js_middlename' => 'PUMBAYA',
                'js_lastname' => 'UMPAR',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'SITIO BAT-US',
                'js_email' => 'noronesa.umpar@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9703653073',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'MA.GRACE',
                'js_middlename' => 'GAIL GUINTAO',
                'js_lastname' => 'VILLANUEVA',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'BLOCK 3 LOT 5 KADALAG AN',
                'js_email' => 'magrace.villanueva@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9343993246',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'HERMI',
                'js_middlename' => 'JANE MANAPO',
                'js_lastname' => 'VILLORENTE',
                'js_suffix' => null,
                'js_gender' => 'Female',
                'js_age'=> 25,
                'js_address' => 'HDA NAGLO',
                'js_email' => 'hermi.villorente@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9301516027',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],
            [
                'js_firstname' => 'LLOYD',
                'js_middlename' => 'IAN DELA CRUZ',
                'js_lastname' => 'ZAMORA',
                'js_suffix' => null,
                'js_gender' => 'Male',
                'js_age'=> 25,
                'js_address' => 'TERRAVILLE ECOVILLAGE',
                'js_email' => 'lloyd.zamora@gmail.com',
                'js_resume' => null,
                'js_contactnumber' => '9850531796',
                'js_password' => bcrypt('12345678'),
                'js_accstatus' => 'pending',
                'js_image' => null,
                'js_badge' => null,
                'created_at' => '2024-07-12 19:24:13',
                'updated_at' => now(),
            ],

        ]);

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('jobseeker_details');
    }
};
