<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreatePesoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('jobseeker_pesoform', function (Blueprint $table) {
            $table->id('peso_id');
            $table->integer('js_id');
            $table->string('peso_srsid');
            $table->string('peso_fullname');
            $table->string('peso_birthdate');
            $table->string('peso_age');
            $table->string('peso_gender');
            $table->string('peso_civilstatus');
            $table->string('peso_city');
            $table->string('peso_baranggay');
            $table->string('peso_street');
            $table->string('peso_email')->unique();
            $table->string('peso_tel')->nullable();
            $table->string('peso_cell');
            $table->string('peso_employment');
            $table->string('peso_educ');
            $table->string('peso_position');
            $table->string('peso_skills');
            $table->string('peso_work');
            $table->string('peso_4ps');
            $table->string('peso_pwd');
            $table->string('peso_registration');
            $table->string('peso_remarks')->nullable();
            $table->string('peso_office');
            $table->string('peso_type');
            $table->string('peso_class');
            $table->string('peso_program');
            $table->string('peso_event');
            $table->string('peso_transaction');

            $table->timestamps();
        });

        DB::table('jobseeker_pesoform')->insert([
            [
                'peso_id' => 1,
                'js_id' => 1,
                'peso_srsid' => '840747',
                'peso_fullname' => 'MARIVIC CHOME CABALLERO',
                'peso_birthdate' => '1999-11-25',
                'peso_age' => '24yrs and 10mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'ENRIQUE B. MAGALONA (SARAVIA), NEGROS OCCIDENTAL',
                'peso_baranggay' => 'POBLACION II (BARANGAY 2)',
                'peso_street' => 'L.CUAYCONG STREET',
                'peso_email' => 'marivicchome@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09487161185',
                'peso_employment' => 'Unemployed',
                'peso_educ' => '2ND YEAR HIGH SCHOOL/GRADE VIII (FOR K TO 12)',
                'peso_position' => 'HOSTESS',
                'peso_skills' => 'Customer Service, Time Management',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2014-05-15',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => '08 - Placement (as reported by employer)',
                'peso_transaction' => 'Placement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 2,
                'js_id' => 2,
                'peso_srsid' => '11440697',
                'peso_fullname' => 'DEN MARK BAYA GASPAR',
                'peso_birthdate' => '1999-05-12',
                'peso_age' => '25yrs and 4mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY X (ESTADO)',
                'peso_street' => 'HDA. PAZ II',
                'peso_email' => 'denmarkgaspar@gmail.com',
                'peso_tel' => '2345-6789',
                'peso_cell' => '09707208998',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'COLLEGE GRADUATE',
                'peso_position' => 'ADMINISTRATIVE CLERK',
                'peso_skills' => 'Technical Proficiency, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2022-09-29',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => '635 CONG KIKO TUPAD 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 3,
                'js_id' => 3,
                'peso_srsid' => '14485683',
                'peso_fullname' => 'JASON GEVERO INTONG',
                'peso_birthdate' => '1999-11-10',
                'peso_age' => '24yrs and 10mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY VII (POB.)',
                'peso_street' => 'VICTORIAS',
                'peso_email' => 'jasongintong@gmail.com',
                'peso_tel' => '3456-7890',
                'peso_cell' => '09556789423',
                'peso_employment' => 'Employed',
                'peso_educ' => '3RD YEAR COLLEGE LEVEL',
                'peso_position' => 'POLICE OFFICER (PNP)',
                'peso_skills' => 'Physical Fitness, Safety Awareness',
                'peso_work' => 'PNP',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2023-06-19',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => '635 CONG KIKO TUPAD 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 4,
                'js_id' => 4,
                'peso_srsid' => '11447052',
                'peso_fullname' => 'CHRISTIAN BARRIOS CALAYCAY',
                'peso_birthdate' => '2001-11-27',
                'peso_age' => '22y 10mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XXI',
                'peso_street' => 'ZONE VI',
                'peso_email' => 'christian.calaycay@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09502606713',
                'peso_employment' => 'Employed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Street Ambulant Vendor',
                'peso_skills' => 'Technical Proficiency, Physical Fitness',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2022-09-30',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'CONCENTRIX SPECIAL RECRUITMENT ACTIVITY',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 5,
                'js_id' => 5,
                'peso_srsid' => '15787370',
                'peso_fullname' => 'JHON PAUL LAYLON CASTRO',
                'peso_birthdate' => '2000-05-12',
                'peso_age' => '24y 4mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY IX (DAAN BANWA)',
                'peso_street' => 'PRK. 5',
                'peso_email' => 'jhon.castro@gmail.com',
                'peso_tel' => '5678-1234',
                'peso_cell' => '09603960300',
                'peso_employment' => 'Unemployed',
                'peso_educ' => '2nd Year College Level',
                'peso_position' => 'Laborer (Gov)',
                'peso_skills' => 'Physical Fitness, Problem-Solving',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-01-15',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'CONCENTRIX SPECIAL RECRUITMENT ACTIVITY',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 6,
                'js_id' => 6,
                'peso_srsid' => '13053105',
                'peso_fullname' => 'PAUL ORIDINA ALTEJOS',
                'peso_birthdate' => '1995-01-12',
                'peso_age' => '29y 8mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XV-A',
                'peso_street' => 'VICTORIAS CITY',
                'peso_email' => 'paul.altejos@gmail.com',
                'peso_tel' => '8765-4321',
                'peso_cell' => '09652134567',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Company Driver',
                'peso_skills' => 'Attention to Detail, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2023-04-03',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 7,
                'js_id' => 7,
                'peso_srsid' => '12858900',
                'peso_fullname' => 'EDUARDO SEBASTIAN BUOY',
                'peso_birthdate' => '1992-02-12',
                'peso_age' => '32y 7mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XIII',
                'peso_street' => 'VILLA VICTORIAS',
                'peso_email' => 'eduardo.buoy@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09632188553',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Budget Officer IV (Nat’l./Local - SG - 22) (Gov)',
                'peso_skills' => 'Financial Management, Analytical Skills',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2023-03-24',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 8,
                'js_id' => 8,
                'peso_srsid' => '16071736',
                'peso_fullname' => 'JOHN STEPHEN JUTAR DAMIRAY',
                'peso_birthdate' => '2002-06-06',
                'peso_age' => '22y 3mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'MANAPLA, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'PURISIMA',
                'peso_street' => 'HDA. PATLAGAN, BRGY. PURISIMA, MANAPLA, NEGROS OCCIDENTAL',
                'peso_email' => 'johnstephendamiray@gmail.com',
                'peso_tel' => '5678-1234',
                'peso_cell' => '09108789174',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Architectural Draftsman',
                'peso_skills' => 'AutoCAD, Design',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-03-04',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 9,
                'js_id' => 9,
                'peso_srsid' => '874657',
                'peso_fullname' => 'LEAH MAY PEÑACUBA DELA CRUZ',
                'peso_birthdate' => '1993-07-18',
                'peso_age' => '31y 2mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'BACOLod CITY (CAPITAL), NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY 1 (POB.)',
                'peso_street' => 'HDA. NENANG',
                'peso_email' => 'leah.delacruz@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09488164859',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Cashier, Call Center Agent, Service Crew',
                'peso_skills' => 'Customer Service, Teamwork',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2014-04-21',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 10,
                'js_id' => 10,
                'peso_srsid' => '11452980',
                'peso_fullname' => 'DREXVON DAVE CARBONILLAS DUMADA-UG',
                'peso_birthdate' => '1999-12-29',
                'peso_age' => '24y 9mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XVIII-A',
                'peso_street' => 'SITIO LUPA',
                'peso_email' => 'drexvon.dumada-ug@gmail.com',
                'peso_tel' => '8765-4321',
                'peso_cell' => '09074676445',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Construction Laborer',
                'peso_skills' => 'Physical Labor, Teamwork',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2022-10-03',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 11,
                'js_id' => 11,
                'peso_srsid' => '16635612',
                'peso_fullname' => 'REYNOLD DESCARTIN MABILOG',
                'peso_birthdate' => '2001-03-14',
                'peso_age' => '23y 6mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XX',
                'peso_street' => 'ZONE 7',
                'peso_email' => 'reynold.mabilog@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09667387359',
                'peso_employment' => 'Employed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Welder',
                'peso_skills' => 'Welding, Metal Fabrication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-17',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 12,
                'js_id' => 12,
                'peso_srsid' => '16623788',
                'peso_fullname' => 'ARIEL ESCALERA MACABEBE',
                'peso_birthdate' => '2000-08-21',
                'peso_age' => '24y 1mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY VI-A',
                'peso_street' => 'SITIO BOULEVARD',
                'peso_email' => 'ariel.macabebe@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09852106804',
                'peso_employment' => 'Employed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Electric Arc Welder (General)',
                'peso_skills' => 'Welding, Safety Procedures',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-16',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 13,
                'js_id' => 13,
                'peso_srsid' => '15754023',
                'peso_fullname' => 'REY ANTONETTE CAUSING MILLANES',
                'peso_birthdate' => '1998-02-24',
                'peso_age' => '26y 7mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY VI-A',
                'peso_street' => 'ZONE 5, CUBAY',
                'peso_email' => 'antonettemillanes@gmail.com',
                'peso_tel' => '5678-1234',
                'peso_cell' => '09561669093',
                'peso_employment' => 'Employed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Baker (General)',
                'peso_skills' => 'Baking, Food Safety',
                'peso_work' => '4 mos as Food and Beverage Supervisor',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-01-05',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 14,
                'js_id' => 14,
                'peso_srsid' => '16635620',
                'peso_fullname' => 'REYMAR MUYCO TERUEL',
                'peso_birthdate' => '1992-09-14',
                'peso_age' => '32y 0mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY I (POB.)',
                'peso_street' => 'GONZAGA ST.',
                'peso_email' => 'reymar.teruel@gmail.com',
                'peso_tel' => '9876-5432',
                'peso_cell' => '09458092878',
                'peso_employment' => 'Employed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Welder',
                'peso_skills' => 'Welding, Blueprint Reading',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-17',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 15,
                'js_id' => 15,
                'peso_srsid' => '16623857',
                'peso_fullname' => 'JERICO ESTEBAN TRIBACO',
                'peso_birthdate' => '1997-02-27',
                'peso_age' => '27y 7mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XIII',
                'peso_street' => 'VILLA VICTORIAS',
                'peso_email' => 'jerico.tribaco@gmail.com',
                'peso_tel' => '4321-8765',
                'peso_cell' => '09154917029',
                'peso_employment' => 'Employed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Painter',
                'peso_skills' => 'Painting, Attention to Detail',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-16',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 16,
                'js_id' => 16,
                'peso_srsid' => '16623906',
                'peso_fullname' => 'STEPHEN RYAN VILLANUEVA',
                'peso_birthdate' => '1994-02-20',
                'peso_age' => '30y 7mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY VII (POB.)',
                'peso_street' => 'FERMONT VILLAGE, BLK2',
                'peso_email' => 'stephen.villanueva@gmail.com',
                'peso_tel' => '6789-0123',
                'peso_cell' => '09631715171',
                'peso_employment' => 'Employed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Painter',
                'peso_skills' => 'Painting, Color Theory',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-16',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'Employment Facilitation',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 17,
                'js_id' => 17,
                'peso_srsid' => '7305362',
                'peso_fullname' => 'KIMBERLY PERDIGOSA AGAEL',
                'peso_birthdate' => '2001-09-13',
                'peso_age' => '23y 0mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'ENRIQUE B. MAGALONA (SARAVIA), NEGROS OCCIDENTAL',
                'peso_baranggay' => 'DAMGO',
                'peso_street' => 'PUROK PAGASA BARANGAY DAMGO E. B. MAGALONA NEGROS OCCIDENTAL',
                'peso_email' => 'kimberly.agael@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09098466157',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'Grade XII (for K to 12)',
                'peso_position' => 'Accounting Officer',
                'peso_skills' => 'Accounting, Attention to Detail',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2020-01-22',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 18,
                'js_id' => 18,
                'peso_srsid' => '15644823',
                'peso_fullname' => 'TEAH SANTIAGO FRANCO',
                'peso_birthdate' => '2001-06-15',
                'peso_age' => '23y 3mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'ENRIQUE B. MAGALONA (SARAVIA), NEGROS OCCIDENTAL',
                'peso_baranggay' => 'ALICANTE',
                'peso_street' => 'PHASE 13 BLK 2. LOT 41 STREET. THERESE VILLAGE',
                'peso_email' => 'teah.franco@gmail.com',
                'peso_tel' => '8765-4321',
                'peso_cell' => '09123456789',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Quality Assurance Inspector',
                'peso_skills' => 'Quality Control, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2023-12-05',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 19,
                'js_id' => 19,
                'peso_srsid' => '11307037',
                'peso_fullname' => 'ANGELA MAE DENOLONG MAGALLANES',
                'peso_birthdate' => '2000-10-26',
                'peso_age' => '23y 11mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XIV',
                'peso_street' => 'HDA. SAN ANTONIO II',
                'peso_email' => 'angela.magallanes@gmail.com',
                'peso_tel' => '2345-6789',
                'peso_cell' => '09153207517',
                'peso_employment' => 'Unemployed',
                'peso_educ' => '4th Year College Level',
                'peso_position' => 'Policewoman',
                'peso_skills' => 'Law Enforcement, Communication Skills',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2022-09-12',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 20,
                'js_id' => 20,
                'peso_srsid' => '16869151',
                'peso_fullname' => 'MERRY JOY JALIPA PABALINAS',
                'peso_birthdate' => '2000-08-16',
                'peso_age' => '24y 1mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Married',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XIV',
                'peso_street' => 'HDA. SAN RAMON',
                'peso_email' => 'merry.pabalinas@gmail.com',
                'peso_tel' => '3456-7890',
                'peso_cell' => '09123456790',
                'peso_employment' => 'Unemployed',
                'peso_educ' => '3rd Year College Level',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Service, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-06-21',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 21,
                'js_id' => 21,
                'peso_srsid' => '8829652',
                'peso_fullname' => 'JOYCE MARIE ILISAN PARREÑO',
                'peso_birthdate' => '1998-02-19',
                'peso_age' => '26y 7mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'BACOLOD CITY (CAPITAL), NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY 20 (POB.)',
                'peso_street' => 'NONE',
                'peso_email' => 'parrejoyce@gmail.com',
                'peso_tel' => 'NONE',
                'peso_cell' => '09452811462',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Accounting Assistant',
                'peso_skills' => 'Accounting, Attention to Detail',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2021-07-02',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 22,
                'js_id' => 22,
                'peso_srsid' => '9318289',
                'peso_fullname' => 'KENNY SAMSON RAGANAS',
                'peso_birthdate' => '1999-07-05',
                'peso_age' => '25y 2mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY IX (DAAN BANWA)',
                'peso_street' => 'PUROK 8',
                'peso_email' => 'kenny.ragan@gmail.com',
                'peso_tel' => 'NONE',
                'peso_cell' => '09155211314',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'High School Graduate',
                'peso_position' => 'Storekeeper',
                'peso_skills' => 'Inventory Management, Organization',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2021-09-21',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 23,
                'js_id' => 23,
                'peso_srsid' => '9439169',
                'peso_fullname' => 'DAVID JOHN RITO RUBIDO',
                'peso_birthdate' => '2000-03-25',
                'peso_age' => '24y 6mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY IX (DAAN BANWA)',
                'peso_street' => 'PUROK 6',
                'peso_email' => 'david.rubido@gmail.com',
                'peso_tel' => 'NONE',
                'peso_cell' => '09567415383',
                'peso_employment' => 'Unemployed',
                'peso_educ' => '3rd Year College Level',
                'peso_position' => 'Accounts Manager, Financial Analyst',
                'peso_skills' => 'Financial Analysis, Team Leadership',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2021-10-15',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 24,
                'js_id' => 24,
                'peso_srsid' => '16869042',
                'peso_fullname' => 'VIJAY JULIAN CEASAR SINORO STA. ANA',
                'peso_birthdate' => '1998-07-01',
                'peso_age' => '26y 2mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XIX-A',
                'peso_street' => 'SOUTH BACAYAN',
                'peso_email' => 'vijay.staana@gmail.com',
                'peso_tel' => 'NONE',
                'peso_cell' => 'NONE',
                'peso_employment' => 'Unemployed',
                'peso_educ' => '2nd Year College Level',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Service, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-06-21',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 25,
                'js_id' => 25,
                'peso_srsid' => '16641910',
                'peso_fullname' => 'ALLYANA MAE CASIPLE ANDICO',
                'peso_birthdate' => '2004-03-25',
                'peso_age' => '20y 6mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'SILAY CITY, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'EUSTAQUIO LOPEZ',
                'peso_street' => 'PUROK NANGKA',
                'peso_email' => 'allyana.andico@gmail.com',
                'peso_tel' => '9876-5432',
                'peso_cell' => '09123456791',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Service, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-20',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING EVENT MAY 17, 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 26,
                'js_id' => 26,
                'peso_srsid' => '16723730',
                'peso_fullname' => 'JESSA TEGUIHAN CABALLERO',
                'peso_birthdate' => '2002-03-25',
                'peso_age' => '22y 6mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XXI',
                'peso_street' => 'RELOCATION SITE',
                'peso_email' => 'jessa.caballero@gmail.com',
                'peso_tel' => '6789-0123',
                'peso_cell' => '09123456792',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Service, Problem Solving',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-06-03',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING EVENT MAY 17, 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 27,
                'js_id' => 27,
                'peso_srsid' => '16641354',
                'peso_fullname' => 'JOSHUA ACALLAR DOMANIEL',
                'peso_birthdate' => '2002-09-16',
                'peso_age' => '22y 0mos',
                'peso_gender' => 'Male',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY X (ESTADO)',
                'peso_street' => 'HDA PAZ I',
                'peso_email' => 'joshua.domaniel@gmail.com',
                'peso_tel' => '2345-6789',
                'peso_cell' => '09123456793',
                'peso_employment' => 'Unemployed',
                'peso_educ' => '2nd Year College Level',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Support, Time Management',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-20',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING EVENT MAY 17, 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 28,
                'js_id' => 10,
                'peso_srsid' => '16648438',
                'peso_fullname' => 'QUEENE ELISAN',
                'peso_birthdate' => '2000-04-26',
                'peso_age' => '24y 5mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY VI (POB.)',
                'peso_street' => 'SALVACION VILLAGE',
                'peso_email' => 'queene.elisan@gmail.com',
                'peso_tel' => '1234-5678',
                'peso_cell' => '09123456780',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Service, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-21',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING EVENT MAY 17, 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 29,
                'js_id' => 11,
                'peso_srsid' => '16649129',
                'peso_fullname' => 'RICHLIE FAITH GERMINO',
                'peso_birthdate' => '2000-10-02',
                'peso_age' => '23y 11mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'CITY OF VICTORIAS, NEGROS OCCIDENTAL',
                'peso_baranggay' => 'BARANGAY XIII',
                'peso_street' => 'VILLA VICTORIAS',
                'peso_email' => 'richlie.germino@gmail.com',
                'peso_tel' => '2345-6789',
                'peso_cell' => '09123456781',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Service, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-21',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING EVENT MAY 17, 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'peso_id' => 30,
                'js_id' => 12,
                'peso_srsid' => '16640620',
                'peso_fullname' => 'ANGELIKA LIMPANGOG GUILIPA',
                'peso_birthdate' => '1997-12-12',
                'peso_age' => '26y 9mos',
                'peso_gender' => 'Female',
                'peso_civilstatus' => 'Single',
                'peso_city' => 'ENRIQUE B. MAGALONA (SARAVIA), NEGROS OCCIDENTAL',
                'peso_baranggay' => 'POBLACION I (BARANGAY 1)',
                'peso_street' => 'AMADO ALFARO ST.',
                'peso_email' => 'angelika.guilipa@gmail.com',
                'peso_tel' => '3456-7890',
                'peso_cell' => '09123456782',
                'peso_employment' => 'Unemployed',
                'peso_educ' => 'College Graduate',
                'peso_position' => 'Call Center Agent',
                'peso_skills' => 'Customer Service, Communication',
                'peso_work' => 'none',
                'peso_4ps' => 'No',
                'peso_pwd' => 'No',
                'peso_registration' => '2024-05-20',
                'peso_remarks' => 'none',
                'peso_office' => 'Victorias',
                'peso_type' => 'Component City',
                'peso_class' => '4th Class',
                'peso_program' => 'PESO',
                'peso_event' => 'GLOBAL STRATEGIC ONE-DAY HIRING EVENT MAY 17, 2024',
                'peso_transaction' => '08 - Placement (as reported by employer)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('jobseeker_pesoform');
    }
}
